### ISSUE TITLE
Separate BE to different repo.

### ISSUE THREAD

**Issue by SergioKingOne** [SergioKingOne/ecom-beauty#31]
Problem: BE and FE are within the same repo, this may cause problems to mantain.

Proposal: Move BE repo to its own repo.

**Comment by DiegoMendez01** [comment]
Problem: The backend (BE) and frontend (FE) were in the same repository, which could cause maintenance issues.

Action Taken: The backend has been moved to its own repository to make maintenance easier and to keep the projects better organized.

Status: Completed.
